spring.application.name=FleetTelematicsBackend

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/fleet_telematics
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info